//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eraser.Util.Native {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Eraser.Util.Native.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid directory entry..
        /// </summary>
        internal static string Invalid_directory_entry_ {
            get {
                return ResourceManager.GetString("Invalid directory entry.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid FAT cluster: cluster is marked bad..
        /// </summary>
        internal static string Invalid_FAT_cluster__cluster_is_marked_bad_ {
            get {
                return ResourceManager.GetString("Invalid FAT cluster: cluster is marked bad.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid FAT cluster: cluster is marked free..
        /// </summary>
        internal static string Invalid_FAT_cluster__cluster_is_marked_free_ {
            get {
                return ResourceManager.GetString("Invalid FAT cluster: cluster is marked free.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The list of open system handles could not be retrieved..
        /// </summary>
        internal static string The_list_of_open_system_handles_could_not_be_retrieved_ {
            get {
                return ResourceManager.GetString("The list of open system handles could not be retrieved.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The path provided is not volume relative. Volume relative paths must begin with a backslash..
        /// </summary>
        internal static string The_path_provided_is_not_volume_relative__Volume_relative_paths_must_begin_with_a_backslash_ {
            get {
                return ResourceManager.GetString("The path provided is not volume relative. Volume relative paths must begin with a" +
                        " backslash.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The provided directory is a long file name..
        /// </summary>
        internal static string The_provided_directory_is_a_long_file_name_ {
            get {
                return ResourceManager.GetString("The provided directory is a long file name.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The provided file contents will not fit in the allocated file..
        /// </summary>
        internal static string The_provided_file_contents_will_not_fit_in_the_allocated_file_ {
            get {
                return ResourceManager.GetString("The provided file contents will not fit in the allocated file.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The specified cluster is not used..
        /// </summary>
        internal static string The_specified_cluster_is_not_used_ {
            get {
                return ResourceManager.GetString("The specified cluster is not used.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The volume provided is not a FAT12 or FAT16 volume..
        /// </summary>
        internal static string The_volume_provided_is_not_a_FAT12_or_FAT16_volume_ {
            get {
                return ResourceManager.GetString("The volume provided is not a FAT12 or FAT16 volume.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The volume provided is not a FAT12 volume..
        /// </summary>
        internal static string The_volume_provided_is_not_a_FAT12_volume_ {
            get {
                return ResourceManager.GetString("The volume provided is not a FAT12 volume.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The volume provided is not a FAT16 volume..
        /// </summary>
        internal static string The_volume_provided_is_not_a_FAT16_volume_ {
            get {
                return ResourceManager.GetString("The volume provided is not a FAT16 volume.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The volume provided is not a FAT32 volume..
        /// </summary>
        internal static string The_volume_provided_is_not_a_FAT32_volume_ {
            get {
                return ResourceManager.GetString("The volume provided is not a FAT32 volume.", resourceCulture);
            }
        }
    }
}
