//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eraser.DefaultPlugins {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Eraser.DefaultPlugins.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} ({1} passes).
        /// </summary>
        internal static string _0____1__passes_ {
            get {
                return ResourceManager.GetString("{0} ({1} passes)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} (1 pass).
        /// </summary>
        internal static string _0___1_pass_ {
            get {
                return ResourceManager.GetString("{0} (1 pass)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} did not have its cluster tips erased, because it is a system file.
        /// </summary>
        internal static string _0__did_not_have_its_cluster_tips_erased__because_it_is_a_system_file {
            get {
                return ResourceManager.GetString("{0} did not have its cluster tips erased, because it is a system file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} did not have its cluster tips erased. The error returned was: {1}.
        /// </summary>
        internal static string _0__did_not_have_its_cluster_tips_erased__The_error_returned_was___1_ {
            get {
                return ResourceManager.GetString("{0} did not have its cluster tips erased. The error returned was: {1}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} did not have its cluster tips erased because it is a hard link or a symbolic link..
        /// </summary>
        internal static string _0__did_not_have_its_cluster_tips_erased_because_it_is_a_hard_link_or_a_symbolic_link_ {
            get {
                return ResourceManager.GetString("{0} did not have its cluster tips erased because it is a hard link or a symbolic " +
                        "link.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} did not have its cluster tips erased because it is compressed, encrypted or a sparse file..
        /// </summary>
        internal static string _0__did_not_have_its_cluster_tips_erased_because_it_is_compressed__encrypted_or_a_sparse_file_ {
            get {
                return ResourceManager.GetString("{0} did not have its cluster tips erased because it is compressed, encrypted or a" +
                        " sparse file.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} did not have its cluster tips erased because of the following error: {1}.
        /// </summary>
        internal static string _0__did_not_have_its_cluster_tips_erased_because_of_the_following_error___1_ {
            get {
                return ResourceManager.GetString("{0} did not have its cluster tips erased because of the following error: {1}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} did not have its cluster tips erased because you do not have the required permissions to erase the file cluster tips..
        /// </summary>
        internal static string _0__did_not_have_its_cluster_tips_erased_because_you_do_not_have_the_required_permissions_to_erase_the_file_cluster_tips_ {
            get {
                return ResourceManager.GetString("{0} did not have its cluster tips erased because you do not have the required per" +
                        "missions to erase the file cluster tips.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (unknown).
        /// </summary>
        internal static string _unknown_ {
            get {
                return ResourceManager.GetString("(unknown)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An invalid erasure method was selected..
        /// </summary>
        internal static string An_invalid_erasure_method_was_selected_ {
            get {
                return ResourceManager.GetString("An invalid erasure method was selected.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на British HMG IS5 (Baseline).
        /// </summary>
        internal static string British_HMG_IS5__Baseline_ {
            get {
                return ResourceManager.GetString("British HMG IS5 (Baseline)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на British HMG IS5 (Enhanced).
        /// </summary>
        internal static string British_HMG_IS5__Enhanced_ {
            get {
                return ResourceManager.GetString("British HMG IS5 (Enhanced)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Constant ({0} bytes).
        /// </summary>
        internal static string Constant___0__bytes_ {
            get {
                return ResourceManager.GetString("Constant ({0} bytes)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copying source files to destination....
        /// </summary>
        internal static string Copying_source_files_to_destination___ {
            get {
                return ResourceManager.GetString("Copying source files to destination...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Could not erase cluster tips in {0} as the volume is not mounted..
        /// </summary>
        internal static string Could_not_erase_cluster_tips_in__0__as_the_volume_is_not_mounted_ {
            get {
                return ResourceManager.GetString("Could not erase cluster tips in {0} as the volume is not mounted.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Could not erase directory entries on the volume {0} because the volume is currently in use..
        /// </summary>
        internal static string Could_not_erase_directory_entries_on_the_volume__0__because_the_volume_is_currently_in_use_ {
            get {
                return ResourceManager.GetString("Could not erase directory entries on the volume {0} because the volume is current" +
                        "ly in use.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Could not erase files and subfolders in {0} because {1}.
        /// </summary>
        internal static string Could_not_erase_files_and_subfolders_in__0__because__1_ {
            get {
                return ResourceManager.GetString("Could not erase files and subfolders in {0} because {1}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Could not force closure of file \&quot;{0}\&quot; {1}(locked by {0}).
        /// </summary>
        internal static string Could_not_force_closure_of_file____0_____1__locked_by__0__ {
            get {
                return ResourceManager.GetString("Could not force closure of file \\\"{0}\\\" {1}(locked by {0})", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Could not list the Alternate Data Streams for file {0} because the file is being used by another process. The file will not be erased..
        /// </summary>
        internal static string Could_not_list_the_Alternate_Data_Streams_for_file__0__because_the_file_is_being_used_by_another_process__The_file_will_not_be_erased_ {
            get {
                return ResourceManager.GetString("Could not list the Alternate Data Streams for file {0} because the file is being " +
                        "used by another process. The file will not be erased.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Default Erasure Methods and PRNGs.
        /// </summary>
        internal static string Default_Erasure_Methods_and_PRNGs {
            get {
                return ResourceManager.GetString("Default Erasure Methods and PRNGs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Drive/Partition.
        /// </summary>
        internal static string Drive_Partition {
            get {
                return ResourceManager.GetString("Drive/Partition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Emptying recycle bin....
        /// </summary>
        internal static string Emptying_recycle_bin___ {
            get {
                return ResourceManager.GetString("Emptying recycle bin...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Eraser.
        /// </summary>
        internal static string Eraser {
            get {
                return ResourceManager.GetString("Eraser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Erasing cluster tips....
        /// </summary>
        internal static string Erasing_cluster_tips___ {
            get {
                return ResourceManager.GetString("Erasing cluster tips...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Erasing incomplete destination file.
        /// </summary>
        internal static string Erasing_incomplete_destination_file {
            get {
                return ResourceManager.GetString("Erasing incomplete destination file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Erasing source files....
        /// </summary>
        internal static string Erasing_source_files___ {
            get {
                return ResourceManager.GetString("Erasing source files...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Erasing unused directory structures....
        /// </summary>
        internal static string Erasing_unused_directory_structures___ {
            get {
                return ResourceManager.GetString("Erasing unused directory structures...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Erasing unused space....
        /// </summary>
        internal static string Erasing_unused_space___ {
            get {
                return ResourceManager.GetString("Erasing unused space...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Files in {0} did not have its cluster tips erased because of the following error: {1}.
        /// </summary>
        internal static string Files_in__0__did_not_have_its_cluster_tips_erased_because_of_the_following_error___1_ {
            get {
                return ResourceManager.GetString("Files in {0} did not have its cluster tips erased because of the following error:" +
                        " {1}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Files in {0} did not have their cluster tips erased because it is a hard link or a symbolic link..
        /// </summary>
        internal static string Files_in__0__did_not_have_their_cluster_tips_erased_because_it_is_a_hard_link_or_a_symbolic_link_ {
            get {
                return ResourceManager.GetString("Files in {0} did not have their cluster tips erased because it is a hard link or " +
                        "a symbolic link.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Files in Folder.
        /// </summary>
        internal static string Files_in_Folder {
            get {
                return ResourceManager.GetString("Files in Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на First/last 16KB Erasure.
        /// </summary>
        internal static string First_last_16KB_Erasure {
            get {
                return ResourceManager.GetString("First/last 16KB Erasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на German VSITR.
        /// </summary>
        internal static string German_VSITR {
            get {
                return ResourceManager.GetString("German VSITR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Gutmann.
        /// </summary>
        internal static string Gutmann {
            get {
                return ResourceManager.GetString("Gutmann", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hard disk {0}.
        /// </summary>
        internal static string Hard_disk__0_ {
            get {
                return ResourceManager.GetString("Hard disk {0}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hard disk {0} ({1}).
        /// </summary>
        internal static string Hard_disk__0____1__ {
            get {
                return ResourceManager.GetString("Hard disk {0} ({1})", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hard disk {0} Partition {1}.
        /// </summary>
        internal static string Hard_disk__0__Partition__1_ {
            get {
                return ResourceManager.GetString("Hard disk {0} Partition {1}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid file path.
        /// </summary>
        internal static string Invalid_file_path {
            get {
                return ResourceManager.GetString("Invalid file path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid folder path.
        /// </summary>
        internal static string Invalid_folder_path {
            get {
                return ResourceManager.GetString("Invalid folder path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Kernel Entropy Source.
        /// </summary>
        internal static string Kernel_Entropy_Source {
            get {
                return ResourceManager.GetString("Kernel Entropy Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Move Source folder to:.
        /// </summary>
        internal static string Move_Source_folder_to_ {
            get {
                return ResourceManager.GetString("Move Source folder to:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Old resident file system table files.
        /// </summary>
        internal static string Old_resident_file_system_table_files {
            get {
                return ResourceManager.GetString("Old resident file system table files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Partition.
        /// </summary>
        internal static string Partition {
            get {
                return ResourceManager.GetString("Partition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Partition: {0}.
        /// </summary>
        internal static string Partition___0_ {
            get {
                return ResourceManager.GetString("Partition: {0}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Partition ({0}).
        /// </summary>
        internal static string Partition___0__ {
            get {
                return ResourceManager.GetString("Partition ({0})", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Partition {0}.
        /// </summary>
        internal static string Partition__0_ {
            get {
                return ResourceManager.GetString("Partition {0}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Partition {0} ({1}).
        /// </summary>
        internal static string Partition__0____1__ {
            get {
                return ResourceManager.GetString("Partition {0} ({1})", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Plausible deniability was selected, but no decoy files were found. The current file has been only replaced with random data..
        /// </summary>
        internal static string Plausible_deniability_was_selected__but_no_decoy_files_were_found__The_current_file_has_been_only_replaced_with_random_data_ {
            get {
                return ResourceManager.GetString("Plausible deniability was selected, but no decoy files were found. The current fi" +
                        "le has been only replaced with random data.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pseudorandom Data.
        /// </summary>
        internal static string Pseudorandom_Data {
            get {
                return ResourceManager.GetString("Pseudorandom Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Random.
        /// </summary>
        internal static string Random {
            get {
                return ResourceManager.GetString("Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Random Data.
        /// </summary>
        internal static string Random_Data {
            get {
                return ResourceManager.GetString("Random Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на RCMP TSSIT OPS-II.
        /// </summary>
        internal static string RCMP_TSSIT_OPS_II {
            get {
                return ResourceManager.GetString("RCMP TSSIT OPS-II", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Recycle Bin.
        /// </summary>
        internal static string Recycle_Bin {
            get {
                return ResourceManager.GetString("Recycle Bin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на recyclebin          Erases files and folders in the recycle bin.
        /// </summary>
        internal static string recyclebin__________Erases_files_and_folders_in_the_recycle_bin {
            get {
                return ResourceManager.GetString("recyclebin          Erases files and folders in the recycle bin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Removing folders....
        /// </summary>
        internal static string Removing_folders___ {
            get {
                return ResourceManager.GetString("Removing folders...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Removing temporary files....
        /// </summary>
        internal static string Removing_temporary_files___ {
            get {
                return ResourceManager.GetString("Removing temporary files...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на RNGCryptoServiceProvider.
        /// </summary>
        internal static string RNGCryptoServiceProvider {
            get {
                return ResourceManager.GetString("RNGCryptoServiceProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Russian GOST P50739-95.
        /// </summary>
        internal static string Russian_GOST_P50739_95 {
            get {
                return ResourceManager.GetString("Russian GOST P50739-95", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save Source file to.
        /// </summary>
        internal static string Save_Source_file_to {
            get {
                return ResourceManager.GetString("Save Source file to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Schneier 7 pass.
        /// </summary>
        internal static string Schneier_7_pass {
            get {
                return ResourceManager.GetString("Schneier 7 pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Searching for files&apos; cluster tips....
        /// </summary>
        internal static string Searching_for_files__cluster_tips___ {
            get {
                return ResourceManager.GetString("Searching for files\' cluster tips...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Secure move.
        /// </summary>
        internal static string Secure_move {
            get {
                return ResourceManager.GetString("Secure move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Securely move {0}.
        /// </summary>
        internal static string Securely_move__0_ {
            get {
                return ResourceManager.GetString("Securely move {0}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Securely moving files and folders....
        /// </summary>
        internal static string Securely_moving_files_and_folders___ {
            get {
                return ResourceManager.GetString("Securely moving files and folders...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select the Source file.
        /// </summary>
        internal static string Select_the_Source_file {
            get {
                return ResourceManager.GetString("Select the Source file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select the Source folder.
        /// </summary>
        internal static string Select_the_Source_folder {
            get {
                return ResourceManager.GetString("Select the Source folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The custom erasure method can only comprise passes containing constant or random passes.
        /// </summary>
        internal static string The_custom_erasure_method_can_only_comprise_passes_containing_constant_or_random_passes {
            get {
                return ResourceManager.GetString("The custom erasure method can only comprise passes containing constant or random " +
                        "passes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The destination directory cannot be within the source directory..
        /// </summary>
        internal static string The_destination_directory_cannot_be_within_the_source_directory_ {
            get {
                return ResourceManager.GetString("The destination directory cannot be within the source directory.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The drive {0} has disk quotas active. This will prevent the complete erasure of unused space and may pose a security concern..
        /// </summary>
        internal static string The_drive__0__has_disk_quotas_active__This_will_prevent_the_complete_erasure_of_unused_space_and_may_pose_a_security_concern_ {
            get {
                return ResourceManager.GetString("The drive {0} has disk quotas active. This will prevent the complete erasure of u" +
                        "nused space and may pose a security concern.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The Drive erasure target requires a volume or physical drive selected for erasure..
        /// </summary>
        internal static string The_Drive_erasure_target_requires_a_volume_or_physical_drive_selected_for_erasure_ {
            get {
                return ResourceManager.GetString("The Drive erasure target requires a volume or physical drive selected for erasure" +
                        ".", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The Eraser Project.
        /// </summary>
        internal static string The_Eraser_Project {
            get {
                return ResourceManager.GetString("The Eraser Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The file {0} could not be erased because the file is currently in used by another application..
        /// </summary>
        internal static string The_file__0__could_not_be_erased_because_the_file_is_currently_in_used_by_another_application_ {
            get {
                return ResourceManager.GetString("The file {0} could not be erased because the file is currently in used by another" +
                        " application.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The file {0} could not be erased because the file&apos;s permissions prevent access to the file..
        /// </summary>
        internal static string The_file__0__could_not_be_erased_because_the_file_s_permissions_prevent_access_to_the_file_ {
            get {
                return ResourceManager.GetString("The file {0} could not be erased because the file\'s permissions prevent access to" +
                        " the file.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The file {0} could not be erased because the file was either compressed, encrypted or a sparse file..
        /// </summary>
        internal static string The_file__0__could_not_be_erased_because_the_file_was_either_compressed__encrypted_or_a_sparse_file_ {
            get {
                return ResourceManager.GetString("The file {0} could not be erased because the file was either compressed, encrypte" +
                        "d or a sparse file.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The file {0} is a hard link or a symbolic link thus the contents of the file was not erased..
        /// </summary>
        internal static string The_file__0__is_a_hard_link_or_a_symbolic_link_thus_the_contents_of_the_file_was_not_erased_ {
            get {
                return ResourceManager.GetString("The file {0} is a hard link or a symbolic link thus the contents of the file was " +
                        "not erased.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The file {0} is currently in use and cannot be removed..
        /// </summary>
        internal static string The_file__0__is_currently_in_use_and_cannot_be_removed_ {
            get {
                return ResourceManager.GetString("The file {0} is currently in use and cannot be removed.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The file {0} was not erased as the file does not exist..
        /// </summary>
        internal static string The_file__0__was_not_erased_as_the_file_does_not_exist_ {
            get {
                return ResourceManager.GetString("The file {0} was not erased as the file does not exist.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The file {0} was not erased because it was deleted before it could be erased..
        /// </summary>
        internal static string The_file__0__was_not_erased_because_it_was_deleted_before_it_could_be_erased_ {
            get {
                return ResourceManager.GetString("The file {0} was not erased because it was deleted before it could be erased.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The file {0} was not erased because the containing directory was deleted before it could be erased..
        /// </summary>
        internal static string The_file__0__was_not_erased_because_the_containing_directory_was_deleted_before_it_could_be_erased_ {
            get {
                return ResourceManager.GetString("The file {0} was not erased because the containing directory was deleted before i" +
                        "t could be erased.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The First/last 16KB erasure method requires another erasure method to erase the file.\n\nThis must be set in the Plugin Settings dialog..
        /// </summary>
        internal static string The_First_last_16KB_erasure_method_requires_another_erasure_method_to_erase_the_file__n_nThis_must_be_set_in_the_Plugin_Settings_dialog_ {
            get {
                return ResourceManager.GetString("The First/last 16KB erasure method requires another erasure method to erase the f" +
                        "ile.\\n\\nThis must be set in the Plugin Settings dialog.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The folder {0} cannot be deleted as it is not empty..
        /// </summary>
        internal static string The_folder__0__cannot_be_deleted_as_it_is_not_empty_ {
            get {
                return ResourceManager.GetString("The folder {0} cannot be deleted as it is not empty.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The folder {0} could not be deleted because the folder&apos;s permissions prevents the deletion of the folder..
        /// </summary>
        internal static string The_folder__0__could_not_be_deleted_because_the_folder_s_permissions_prevents_the_deletion_of_the_folder_ {
            get {
                return ResourceManager.GetString("The folder {0} could not be deleted because the folder\'s permissions prevents the" +
                        " deletion of the folder.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The folder {0} was not erased because the containing directory was deleted before it could be erased..
        /// </summary>
        internal static string The_folder__0__was_not_erased_because_the_containing_directory_was_deleted_before_it_could_be_erased_ {
            get {
                return ResourceManager.GetString("The folder {0} was not erased because the containing directory was deleted before" +
                        " it could be erased.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The input text is invalid for the current data type. Valid hexadecimal characters are the digits 0-9 and letters A-F.
        /// </summary>
        internal static string The_input_text_is_invalid_for_the_current_data_type__Valid_hexadecimal_characters_are_the_digits_0_9_and_letters_A_F {
            get {
                return ResourceManager.GetString("The input text is invalid for the current data type. Valid hexadecimal characters" +
                        " are the digits 0-9 and letters A-F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The method needs to have at least one pass defined..
        /// </summary>
        internal static string The_method_needs_to_have_at_least_one_pass_defined_ {
            get {
                return ResourceManager.GetString("The method needs to have at least one pass defined.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The name of the custom method cannot be empty..
        /// </summary>
        internal static string The_name_of_the_custom_method_cannot_be_empty_ {
            get {
                return ResourceManager.GetString("The name of the custom method cannot be empty.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The partition table on the drive could not be erased..
        /// </summary>
        internal static string The_partition_table_on_the_drive_could_not_be_erased_ {
            get {
                return ResourceManager.GetString("The partition table on the drive could not be erased.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The pass constant cannot be displayed as text because it contains invalid characters..
        /// </summary>
        internal static string The_pass_constant_cannot_be_displayed_as_text_because_it_contains_invalid_characters_ {
            get {
                return ResourceManager.GetString("The pass constant cannot be displayed as text because it contains invalid charact" +
                        "ers.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The pass constant must not be empty..
        /// </summary>
        internal static string The_pass_constant_must_not_be_empty_ {
            get {
                return ResourceManager.GetString("The pass constant must not be empty.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The path you selected is invalid..
        /// </summary>
        internal static string The_path_you_selected_is_invalid_ {
            get {
                return ResourceManager.GetString("The path you selected is invalid.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The program does not have the required permissions to erase the disk..
        /// </summary>
        internal static string The_program_does_not_have_the_required_permissions_to_erase_the_disk_ {
            get {
                return ResourceManager.GetString("The program does not have the required permissions to erase the disk.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The program does not have the required permissions to erase the disk. Run the program as an administrator and retry the operation..
        /// </summary>
        internal static string The_program_does_not_have_the_required_permissions_to_erase_the_disk__Run_the_program_as_an_administrator_and_retry_the_operation_ {
            get {
                return ResourceManager.GetString("The program does not have the required permissions to erase the disk. Run the pro" +
                        "gram as an administrator and retry the operation.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The program does not have the required permissions to erase the unused space on disk..
        /// </summary>
        internal static string The_program_does_not_have_the_required_permissions_to_erase_the_unused_space_on_disk_ {
            get {
                return ResourceManager.GetString("The program does not have the required permissions to erase the unused space on d" +
                        "isk.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The program does not have the required permissions to erase the unused space on disk. Run the program as an administrator and retry the operation..
        /// </summary>
        internal static string The_program_does_not_have_the_required_permissions_to_erase_the_unused_space_on_disk__Run_the_program_as_an_administrator_and_retry_the_operation_ {
            get {
                return ResourceManager.GetString("The program does not have the required permissions to erase the unused space on d" +
                        "isk. Run the program as an administrator and retry the operation.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The selected erasure method is not supported for this erasure target..
        /// </summary>
        internal static string The_selected_erasure_method_is_not_supported_for_this_erasure_target_ {
            get {
                return ResourceManager.GetString("The selected erasure method is not supported for this erasure target.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The task was cancelled..
        /// </summary>
        internal static string The_task_was_cancelled_ {
            get {
                return ResourceManager.GetString("The task was cancelled.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This computer has had System Restore or Volume Shadow Copies enabled. This may allow copies of files stored on the disk to be recovered and pose a security concern..
        /// </summary>
        internal static string This_computer_has_had_System_Restore_or_Volume_Shadow_Copies_enabled__This_may_allow_copies_of_files_stored_on_the_disk_to_be_recovered_and_pose_a_security_concern_ {
            get {
                return ResourceManager.GetString("This computer has had System Restore or Volume Shadow Copies enabled. This may al" +
                        "low copies of files stored on the disk to be recovered and pose a security conce" +
                        "rn.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unused disk space.
        /// </summary>
        internal static string Unused_disk_space {
            get {
                return ResourceManager.GetString("Unused disk space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unused disk space ({0}).
        /// </summary>
        internal static string Unused_disk_space___0__ {
            get {
                return ResourceManager.GetString("Unused disk space ({0})", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на US Air Force 5020.
        /// </summary>
        internal static string US_Air_Force_5020 {
            get {
                return ResourceManager.GetString("US Air Force 5020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на US Army AR380-19.
        /// </summary>
        internal static string US_Army_AR380_19 {
            get {
                return ResourceManager.GetString("US Army AR380-19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на US DoD 5220.22-M (8-306./E).
        /// </summary>
        internal static string US_DoD_5220_22_M__8_306__E_ {
            get {
                return ResourceManager.GetString("US DoD 5220.22-M (8-306./E)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на US DoD 5220.22-M (8-306./E, C &amp; E).
        /// </summary>
        internal static string US_DoD_5220_22_M__8_306__E__C___E_ {
            get {
                return ResourceManager.GetString("US DoD 5220.22-M (8-306./E, C & E)", resourceCulture);
            }
        }
    }
}
